name: Continuous Integration
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nx set SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Format code
        run: npx nx format:check

      - name: Lint code
        run: npx nx affected -t lint --parallel=3

      - name: Danger
        run: npx danger ci --dangerfile=./.github/actions/dangerfile/dangerfile.ts ${{ github.event.number }} --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nx set SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Test code
        run: npx nx affected -t test --parallel=3 --configuration=ci

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nx set SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Build code
        run: npx nx affected -t build --parallel=3
